name: Deploy Images to GHCR

env:
  DOTNET_VERSION: "6.0.x"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GH_PAT}}

      - name: "Build Inventory Image"
        run: |
          docker buildx build --push --platform linux/amd64 --tag ghcr.io/valdearg/extract_archives:0.0.1 --tag ghcr.io/valdearg/extract_archives:latest .
